INSERT INTO audio_metadata (
       file_path,
       track_name,
       contributing_artist,
       album,
       album_artist,
       composer,
       track_year,
       track_number_position,
       part_of_set,
       rating,
       lyrics,
       play_count,
       file_extension,
       duration,
       file_size,
       bit_rate,
       frequency_index,
       version_id3_tag,
       date_change,
       layer_descriptio,
       comments,
       content_type,
       track_text,
       publisher,
       mpeg_version,
       channel_mode,
       parent_folder
)
values (
      'D:\Temp\0_feder_goodbye_feat_lyse_myzuka.org.mp3',
      'Goodbye feat. Lyse (Original Mix)',
      'Feder',
      'Goodbye (feat. Lyse)',
      'Feder feat Lyse',
      '',
      '2014',
      '1/13',
      '2/4',
      '',
      'ssss',
      0,
      'mp3',
      290,
      0,
      320,
      44100,
      'ID3v1/ID3v2',
      '',
      'Layer 3',
      '(myzuka.ru)',
      'Deep House',
      'sdfasdfadsf',
      'Emprise Music',
      'MPEG-1',
      'Stereo',
      6  
)